import '@/styles/globals.css'
import '@/styles/font-face.css'
import 'react-toastify/dist/ReactToastify.css'
import Providers from '@/providers'
import { Vazirmatn } from 'next/font/google'
import { ToastContainer } from 'react-toastify'


export const metadata = {
  title: 'Rexo Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      <body>
        <ToastContainer />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
