import '@/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css'
import Providers from '@/providers'
import { Vazirmatn } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

const vazir = Vazirmatn({ subsets: ['arabic', 'latin'], display: 'swap', variable: "vmtn" })

export const metadata = {
  title: 'Rexo Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      <body className={vazir.className}>
        <ToastContainer />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
